### ISSUE TITLE
Tables always right-align

### ISSUE THREAD

**Issue by Franco-Pretorius** [Franco-Pretorius/Python-Tutorial#12]
The Markdown tables in Unit 6 are always right-aligned, despite using the syntax from the [Markdown tables generator](https://www.tablesgenerator.com/markdown_tables). This issue was also mentioned [here](https://github.com/jupyter/notebook/issues/3919), but I don't really understand their conclusion.

**Comment by rayryeng** [comment]
The conclusion is that using the Jupyter Notebook ecosystem, the right-align bug has not been addressed yet.  Changes have been made but they were made to the Jupyter Lab ecosystem instead.  Therefore, local installations of Jupyter Notebook have not had this bug fixed.  To this day, I have no idea why it is addressed in one and not the other.

**Comment by Franco-Pretorius** [comment]
Thanks for the explanation 😀
