### ISSUE TITLE
Consider using suplots instead of subplot

### ISSUE THREAD

**Issue by alchemyst** [Franco-Pretorius/Python-Tutorial#4]
"Modern" matplotlib usage scorns the use of `subplot()` in favour of [`subplots()`](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.subplots). I've reworked all the plotting the Dynamics and Control notebooks to use this instead.

**Comment by Franco-Pretorius** [comment]
Thanks, it's fixed now :)
