### ISSUE TITLE
Parentheses don't create tuples, commas do

### ISSUE THREAD

**Issue by alchemyst** [Franco-Pretorius/Python-Tutorial#5]
In Unit 1 you mention tuples are associated with parentheses. It's important to highlight that it's the commas that are the syntax for tuples, not the parentheses, but that parentheses are sometimes required:

    a = 1, 2, 3  # works fine to create a tuple

This is explicitly mentioned in [the docs](https://docs.python.org/3.7/library/stdtypes.html#tuples):

> Note that it is actually the comma which makes a tuple, not the parentheses. The parentheses are optional, except in the empty tuple case, or when they are needed to avoid syntactic ambiguity. For example, f(a, b, c) is a function call with three arguments, while f((a, b, c)) is a function call with a 3-tuple as the sole argument.

It also explains why the trailing comma is required to create a one-element tuple:

    one_element_tuple = 1,

    just_one_int = 1

**Comment by Franco-Pretorius** [comment]
Thanks, I've fixed this
