### ISSUE TITLE
Consider removing % formatting

### ISSUE THREAD

**Issue by alchemyst** [Franco-Pretorius/Python-Tutorial#8]
I believe it is not necessary for new users of Python to learn % string interpolation. It's best to start with `format()` and f strings.

**Comment by Franco-Pretorius** [comment]
Thank you, I have revised Units 1-3 to reflect this.

**Comment by alchemyst** [comment]
@Franco-Pretorius If you have resolved this, it's normal practice to close the issue. If you closed it with a particular commit, you can use a commit message like "Removed % formatting, closes #8" and it will automatically close the issue when you push. See [here](https://help.github.com/en/articles/closing-issues-using-keywords) for more info.
